config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root 'splashes#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'splashes#index'
  end

  resources :splashes, only: [:index]
  resources :users
  resources :groups, except: [:edit, :update] do
    resources :entities, except: [:edit, :update]
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, user: user
    can :manage, Entity, user: user

    can %i[read create], Group
    can %i[read create], Entity
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities
  has_one_attached :icon, dependent: :destroy

  validates :name, :icon, presence: true

  def total_transaction
    entities.sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :groups
  has_many :entities

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  load_and_authorize_resource

  def index
    @group = Group.find(params[:group_id])
    @entities = @group.entities.all.order(created_at: :desc)
  end

  def show; end

  def new
    @group = Group.find(params[:group_id])
    @entity = @group.entities.new
  end

  def create
    @group = Group.find(params[:group_id])
    @entity = @group.entities.create!(name: entity_params[:name], amount: entity_params[:amount],
                                      user_id: current_user.id, group_id: @group.id)

    respond_to do |format|
      format.html do
        if @entity.save
          redirect_to group_entities_path(@group.id), notice: 'You have successfully created a transaction.'
        else
          render :new, alert: 'Error: Transaction could not be saved'
        end
      end
    end
  end

  def destroy; end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @groups = current_user.groups.all.includes(icon_attachment: :blob)
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      format.html do
        if @group.save
          redirect_to groups_url, notice: 'You have successfully created a category.'
        else
          render :new, alert: 'Error: Category could not be saved'
        end
      end
    end
  end

  def destroy; end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/_form.html.erb
<%= form_with model: @entity, url: group_entities_path, method: :post, local: true do |form| %>

    <div class="mb-3 p-2">
      <%= form.label :name, "Name", :class => "form-label" %>
      <%= form.text_field :name, placeholder: "Transaction Name", required: true, :class => "form-control" %>
    </div>

    <div class="mb-3 p-2">
      <%= form.label :amount, "Amount", :class => "form-label" %>
      <%= form.number_field :amount, placeholder: "Amount", required: true, :class => "form-control" %>
    </div>

    <div class="p-2">
      <%= form.submit "Save", class: "btn btn-primary", disable_with: "Please wait..." %>
    </div>

<% end %>

app/views/entities/index.html.erb
<div class="d-flex p-2 brand-text">
  <h1><%= @group.name.capitalize %>'s transactions</h1>
</div>

<div class="p-2 text-dark-50">
  <h3>Total spent: <%= @group.total_transaction %></h3>
</div>


<% @entities.each do |entity| %>
  <div class="p-2">
    <div class="card p-2 bg-light">
      <div class="card-body">
        <h5 class="card-title"><%= entity.name %></h5>
        <p class="card-text"><%= entity.amount %></p>
        <p class="card-text"><small class="text-muted"><%= entity.created_at %></small></p>
      </div>
    </div>
  </div>
<% end %>

<div class="p-2">
  <%= link_to "Add transaction", new_group_entity_path(@group, @entity), :class => "btn btn-primary" %>
</div>

app/views/entities/new.html.erb
<h1>Add your transaction</h1>
<%= render "form" %>

app/views/entities/show.html.erb
<h1>Entities#show</h1>
<p>Find me in app/views/entities/show.html.erb</p>

app/views/groups/_form.html.erb
<%= form_with model: @group, method: :post, local: true do |form| %>
    <div class="mb-3 p-2">
      <%= form.label :name, "Name", :class => "form-label" %>
      <%= form.text_field :name, placeholder: "Category Name", required: true, :class => "form-control" %>
    </div>

    <div class="mb-3 p-2">
      <%= form.label :icon, "Icon", :class => "form-label" %>
      <%= form.file_field :icon, placeholder: "Icon link", required: true, :class => "form-control" %>
    </div>

    <div class="p-2">
      <%= form.submit "Save", class: "btn btn-primary", disable_with: "Please wait..." %>
    </div>
<% end %>

app/views/groups/index.html.erb
<h1 class="brand-text text-primary px-2">Categories</h1>
<div class="px-2">
<% @groups.each do |group| %>
  <div class="card mb-3 bg-light" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-4 py-3">
        <% if group.icon.attached? %>
          <img src="<%=(url_for(group.icon))%>" class="img-fluid rounded mx-auto d-block image" alt="..." height = "60">
        <% end %>
      </div>
      <div class="col-8">
        <div class="card-body">
          <%= link_to group_entities_path(group.id) do %>
            <h5 class="card-title"><%= group.name %></h5>
          <% end %>
          <small>Total amount spent: <%= group.total_transaction %></small>
          <p class="card-text"><small class="text-muted"><%= group.created_at %></small></p>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>
<div class="px-2">
  <%= link_to "Add category", new_group_path, :class => "btn btn-primary" %>
</div>

app/views/groups/new.html.erb
<div class="d-flex p-2">
  <h1>Add your category</h1>
</div>
<%= render "form" %>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Shizuru&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render partial: "shared/navbar" %>
    <% end %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
<% if user_signed_in? %>
   <% if current_page?(groups_path) %>
    <%= link_to "Padget", groups_path, class: "logo-nav primary" %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-secondary btn-sm" %> 
  <% elsif current_page?(new_group_path)  %>
      <%= link_to "<", groups_path, class: "back primary" %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-secondary btn-sm" %>
  <% elsif current_page?(group_entities_path(@group.id))  %>
      <%= link_to "<", groups_path, class: "back primary" %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-secondary btn-sm" %>
  <% elsif current_page?(new_group_entity_path(@group, @entity))  %>
      <%= link_to "<", group_entities_path, class: "back primary" %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-secondary btn-sm" %>
  <% end %>
<% end %>
</nav>

app/views/splashes/index.html.erb
<div>
  <div class="p-5">  
    <h1 class="logo-text text-center py-5">Padget</h1>
  </div>
  <div class="d-grid">
    <%= link_to "Log in", new_user_session_path, :class => "btn btn-primary" %><br>
    <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-light" %>
  </div>
</div>